import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

/**
 * API Route: Signup with Referral Tracking
 *
 * Handles user signup with referral code support:
 * 1. Creates auth user
 * 2. Creates customer record
 * 3. If referral code provided:
 *    - Validates code
 *    - Sets referred_by_customer_id
 *    - Sets signup_discount_percentage to 10%
 *    - Creates referral record (status: pending)
 */

// Use service role for customer creation
const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  },
)

export async function POST(request: NextRequest) {
  try {
    const {
      email,
      password,
      fullName,
      businessName,
      referralCode,
      country = 'AU', // Default to Australia
      state,
      city,
    } = await request.json()

    if (!email || !password || !fullName || !businessName) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
    }

    // 1. Validate referral code if provided
    let referrerId: string | null = null
    if (referralCode) {
      const { data: referrer, error: referrerError } = await supabaseAdmin
        .from('customers')
        .select('id')
        .eq('referral_code', referralCode)
        .single()

      if (referrerError || !referrer) {
        return NextResponse.json({ error: 'Invalid referral code' }, { status: 400 })
      }

      referrerId = referrer.id
    }

    // 2. Create auth user
    const { data: authData, error: authError } = await supabaseAdmin.auth.admin.createUser({
      email,
      password,
      email_confirm: true, // Auto-confirm for development
      user_metadata: {
        full_name: fullName,
        business_name: businessName,
      },
    })

    if (authError) {
      console.error('Auth error:', authError)
      return NextResponse.json({ error: authError.message }, { status: 400 })
    }

    if (!authData.user) {
      return NextResponse.json({ error: 'Failed to create user' }, { status: 500 })
    }

    // 3. Create customer record with referral data
    const { data: customer, error: customerError } = await supabaseAdmin
      .from('customers')
      .insert({
        auth_user_id: authData.user.id,
        email,
        name: fullName,
        business_name: businessName,
        country,
        state,
        city,
        referred_by_customer_id: referrerId,
        signup_discount_percentage: referrerId ? 10 : 0, // 10% if referred
        // referral_code will be auto-generated by trigger
      })
      .select()
      .single()

    if (customerError) {
      console.error('Error creating customer:', customerError)
      // Rollback: delete auth user
      await supabaseAdmin.auth.admin.deleteUser(authData.user.id)
      return NextResponse.json({ error: 'Failed to create customer record' }, { status: 500 })
    }

    // 4. Create referral relationship if referred
    if (referrerId && customer) {
      const { error: referralError } = await supabaseAdmin.from('referrals').insert({
        referrer_customer_id: referrerId,
        referred_customer_id: customer.id,
        referral_code_used: referralCode,
        status: 'pending', // Will become 'active' when they subscribe
        referred_at: new Date().toISOString(),
      })

      if (referralError) {
        console.error('Error creating referral:', referralError)
        // Don't rollback - customer was created successfully
        // Referral can be fixed manually if needed
      }
    }

    return NextResponse.json({
      success: true,
      customer: {
        id: customer.id,
        email: customer.email,
        hasReferralDiscount: !!referrerId,
      },
    })
  } catch (error: any) {
    console.error('Error in signup:', error)
    return NextResponse.json(
      { error: 'Internal server error', message: error.message },
      { status: 500 },
    )
  }
}
